### ISSUE TITLE
Create teamleader page

### ISSUE THREAD

**Issue by IonutNechita01** [Evelyne03/Proiect-Colectiv#11]
creeaza pagina pentru teamLeader, adauga si in login chestia asta, momenta o lasi doar cu see my data

**Comment by CezarPetreanu** [comment]
acm ma apuc

**Comment by CezarPetreanu** [comment]
Error: NG04002: Cannot match any routes. URL Segment: 'teamleader/myData'
Error: NG04002: Cannot match any routes. URL Segment: 'teamleader/myData'
    at ApplyRedirects.noMatchError (router.mjs:3656:16)
    at router.mjs:3638:28
    at catchError.js:10:39
    at OperatorSubscriber._error (OperatorSubscriber.js:23:21)
    at OperatorSubscriber.error (Subscriber.js:40:18)
    at OperatorSubscriber._error (Subscriber.js:64:30)
    at OperatorSubscriber.error (Subscriber.js:40:18)
    at OperatorSubscriber._error (Subscriber.js:64:30)
    at OperatorSubscriber.error (Subscriber.js:40:18)
    at OperatorSubscriber._error (Subscriber.js:64:30)
    at resolvePromise (zone.js:1214:31)
    at resolvePromise (zone.js:1168:17)
    at zone.js:1281:17
    at _ZoneDelegate.invokeTask (zone.js:409:31)
    at core.mjs:23896:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:23896:36)
    at _ZoneDelegate.invokeTask (zone.js:408:60)
    at Object.onInvokeTask (core.mjs:24197:33)
    at _ZoneDelegate.invokeTask (zone.js:408:60)
    at Zone.runTask (zone.js:178:47)
handleError @ core.mjs:8400
